# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version("2.61.0")

default_platform :ios

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :run_test do
    run_tests(
      project: "ISupportKit.xcodeproj",
      scheme: "ISupportKit",
      configuration: "Debug",
      device: "iPhone 8"
    )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
